name: GH Management - SQL Project

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build-ghmgmt-sqlproj:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: azure/sql-action@master
        with:        
          connection-string: ${{ secrets.GH_MGMT_CONNECTION_STRING }}
          project-file: 'src/sqldb/sqldb.sqlproj'