name: UAT - Docker - Approval System Container

on:
  push:
    branches:
      - uat
    paths:
      - "src/goapp/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: src/goapp

jobs:
  build-goapp-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.ACR_REGISTRY }}/uat-approval-system-app:${{ github.sha }} -t ${{ secrets.ACR_REGISTRY }}/uat-approval-system-app:latest
          docker push ${{ secrets.ACR_REGISTRY }}/uat-approval-system-app